apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ac-test
  namespace: ac-test
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
