apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: ac-internal
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-image-updater-config","app.kubernetes.io/part-of":"argocd-image-updater"},"name":"argocd-image-updater-config","namespace":"ac-internal"}}
data:
  registries.conf: |
    registries:
    - name: Private Registry
      prefix: ac-registry-ac-internal
      ping: yes
      default: true
      api_url: https://ac-registry-ac-internal.dev.cluster02.fis-cloud.xplat.online
      credentials: pullsecret:ac-internal/private-registry
binaryData: {}
