apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: ac-internal
  annotations:
    argocd-image-updater.argoproj.io/image-list: guestbook=quay.io/minhnv82/guestbook:v1
    argocd-image-updater.argoproj.io/guestbook.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/pull-policy: "Always"
spec:
  project: default
  source:
    repoURL: "https://github.com/ngovanminh3232/argocd-example.git"
    targetRevision: master
    path: environment/ac-internal/guestbook/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ac-internal
  syncPolicy: {}