---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: ac-internal
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-app=ac-registry-ac-internal.dev.cluster02.fis-cloud.xplat.online/argocd/nginx-122:v1
    argocd-image-updater.argoproj.io/my-app.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/pull-policy: "Always"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ngovanminh3232/argocd-example.git
    targetRevision: master
    path: my-app-chart
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: "ac-registry-ac-internal.dev.cluster02.fis-cloud.xplat.online/argocd/nginx-122"
        - name: "image.tag"
          value: v1
      values: |
        imagePullSecrets:
          - name: private-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: ac-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
