apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: ac-registry-ac-internal.dev.cluster02.fis-cloud.xplat.online/argocd/guestbook:v1
        name: guestbook-ui
        ports:
        - containerPort: 80
