---
namespace: ac-internal
replicas:
  - name: guestbook-ui
    count: 2

images:
  - name: ac-registry-ac-internal.dev.cluster02.fis-cloud.xplat.online/argocd/guestbook
    newTag: v1

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: private-registry }]

resources:
  - ../../../guestbook